### ISSUE TITLE
Вебхуки-уведомления - возвращаемые значения

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#63]
На уведомления "Создать магазин/терминал" сервис партнера должен вернуть некие uuid, Поясните, пожалуйста, что это за uuid?

**Comment by Lytkini** [comment]
Добрый день.
Это тот же идентификатор, который уходит от Эвотора в запросе. Он нужен нам в качестве подтверждения, что вы создали у себя эту сущность.
PartnerId – нигде не используется и при следующем обновлении будет удалён из документации.

**Comment by aleynikov-ae** [comment]
Хорош спамить 


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: Nikita Churilov <notifications@github.com> Дата: 11.11.17  13:05  (GMT+04:00) Кому: evotor/documentation-api <documentation-api@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: Re: [evotor/documentation-api] Вебхуки-уведомления - возвращаемые значения (#63) 
Closed #63.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/evotor/documentation-api","title":"evotor/documentation-api","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/evotor/documentation-api"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #63."}],"action":{"name":"View Issue","url":"https://github.com/evotor/documentation-api/issues/63#event-1337166253"}}}
